<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function fineNear($lat, $lon)
    {
        $distance = 1;
        $results = $this->getEntityManager()
            ->createQuery(
                "SELECT DISTINCT e,(((acos(sin((".$lat."*pi()/180)) *
            sin((e.lat*pi()/180))+cos((".$lat."*pi()/180)) *
            cos((e.lat*pi()/180)) * cos(((".$lon."- e.long)*
            pi()/180))))*180/pi())*60*1.1515
        ) as distance
        FROM AppBundle:Event e
        HAVING distance <= ".$distance."
        ORDER BY distance DESC")
            ->getResult();
        $events = array();
        foreach($results as $result) {
            $event = $result[0];

            if (!in_array($event, $events)) {
                $event->setDistance($result['distance']);
                $events[] = $event;
            }
        }
        return $events;
    }
}
